In [1]:
import numpy as np


In [3]:
A = np.array([1, 2, 3])
B = np.array([4, 3, 6])

In [4]:
A

array([1, 2, 3])

In [5]:
B

array([4, 3, 6])

In [6]:
np.add(A, B)

array([5, 5, 9])

In [7]:
np.subtract(B, A)

array([3, 1, 3])

In [8]:
np.multiply(A, B)

array([ 4,  6, 18])

In [9]:
np.divide(A, B)

array([0.25      , 0.66666667, 0.5       ])

In [11]:
np.power(A, 2)

array([1, 4, 9])