NumPy stands for numerical python
NumPy is all about array and matrices
NumPy is called (ndarray)

In [8]:
#import NumPy Library 
import numpy as np

In [9]:
# first NumPy array
first_numpy_array = np.array([1,2,3,4])

This is just a test for the notebook in how to use markdown

In [10]:
# Print first array
print (first_numpy_array)

[1 2 3 4]


In [12]:
# Array with zeros
array_with_zeros = np.zeros((3,3))
print (array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# Array with ones 
array_with_ones = np.ones((3, 3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# array with empty
array_with_empty = np.empty((2, 3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# array with arange mothod
np_arange = np.arange(12)
print (np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [22]:
# reshape method to change / create array
np_arange.reshape(3, 4)
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [28]:
# Linspace for linearly (equal) spaced data elements
# linspace(first element, second element, total number of equidistant element)
np_linspce = np.linspace(1, 6, 5)
np_linspce

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [29]:
# one dimensional array
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [31]:
# Two dimensional array
twoD_array = oneD_array.reshape(3, 5)
print(twoD_array) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [35]:
# Three dimensional array
theeD_array = np.arange(27).reshape(3, 3, 3)
print(theeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
