In [1]:
import numpy as np

In [2]:
# 0D array
np.array(24)

array(24)

In [3]:
# 1D array
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [6]:
# 2D array
np.array([[1, 1, 1],[1, 2, 1]])

array([[1, 1, 1],
       [1, 2, 1]])

In [10]:
# 3D array
np.array(
    [
        [
            [1, 1, 1],
            [2, 2, 2]
        ],
        [
            [3, 3, 3],
            [4, 4, 4]
        ]
    ]
)

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [11]:
# Store array in a variable
numpy_array = np.array(
    [
        [
            [1, 1, 1],
            [2, 2, 2]
        ],
        [
            [3, 3, 3],
            [4, 4, 4]
        ]
    ]
)

In [13]:
# Shape of the array is like an array 2 rows 3 columns
# But here its 3D array so the result is:
numpy_array.shape

(2, 2, 3)

In [16]:
# Print how many dimns in array
numpy_array.ndim

3