In [1]:
import numpy as np

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7,8,9],[10, 11, 12]]])

Accessing different elements of an array

In [4]:
arr_1d[0]

1

In [5]:
arr_1d[1]

2

In [6]:
arr_1d[-3
       ]

4

In [7]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr_2d[0, 0]

1

In [9]:
arr_2d[0, 1]

2

In [10]:
arr_2d[1, -1]

6

In [11]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
arr_3d[0, 1, 2]

6

In [14]:
arr_3d[1, 1, -1]

12

Slicing an array

In [15]:
arr_1d[1:]

array([2, 3, 4, 5, 6])

In [16]:
arr_1d[3:5]

array([4, 5])

In [17]:
arr_1d[-3:-1]

array([4, 5])

In [18]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr_2d[1,1:]

array([5, 6])

In [22]:
arr_2d[-2:-3:-1]

array([[1, 2, 3]])

In [23]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr_3d[1:1:1]

array([], shape=(0, 2, 3), dtype=int64)