In [1]:
import numpy as np

In [2]:
arr = np.array([[4, 3, 2],[10, 1, 0], [5, 8, 24]])

In [3]:
arr


array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [8]:
# # The np.amin() function in numpy returns the minimum of an array or minium along an axis.
np.amin(arr)

0

In [7]:
# When use np.amin(arr, axis=0) it will return the minimum value along the vertical axis (axis=0) for each column

np.amin(arr, axis=0)

array([4, 1, 0])

In [10]:
np.amin(arr, axis=1)

array([2, 0, 5])

In [11]:
np.amax(arr, axis=1)

array([ 4, 10, 24])