In [ ]:
import numpy as np

In [ ]:
# generate array using x in range
numpy_array = np.array([x for x in range(1, 10)])
numpy_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Conver array to 3 by 3 array
numpy_array.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
numpy_array = np.array([x for x in range(1, 13)])

In [ ]:
# reshape to 3D array
numpy_array.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# the length of 1D array must be equal to product of 3D array
numpy_array.reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [15]:
# reshape fo unkown dims alos helpful when using dynamic datasets
numpy_array.reshape(2, 2, -1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
# Floaten the array
numpy_arr = numpy_array.reshape(3, 2, 2)


In [17]:
numpy_arr.reshape(-1) # this -1 will flatent the array
# print(flaten_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])